"""added gen column to projects

Revision ID: 006f14622c47
Revises: 81298bf87dea
Create Date: 2025-10-09 23:25:30.139990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006f14622c47'
down_revision = '81298bf87dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generator_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('generator_config')



    # ### end Alembic commands ###
