"""quote id added to invoice and jobcards tables

Revision ID: 0b59911cc118
Revises: 9269a04048ab
Create Date: 2025-10-15 14:16:34.006478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b59911cc118'
down_revision = '9269a04048ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'documents', ['quote_id'], ['id'])

    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_job_card_id', ['job_card_id'], unique=False)
        batch_op.create_index('ix_attachments_uploaded_by', ['uploaded_by_id'], unique=False)

    with op.batch_alter_table('job_card_materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_job_card_id', ['job_card_id'], unique=False)
        batch_op.create_index('ix_materials_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('job_card_time_entries', schema=None) as batch_op:
        batch_op.create_index('ix_time_entries_job_card_id', ['job_card_id'], unique=False)
        batch_op.create_index('ix_time_entries_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_job_cards_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_job_cards_client_id', ['client_id'], unique=False)
        batch_op.create_index('ix_job_cards_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('ix_job_cards_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_job_cards_status', ['status'], unique=False)
        batch_op.create_index('ix_job_cards_vehicle_id', ['vehicle_id'], unique=False)
        batch_op.create_foreign_key(None, 'documents', ['quote_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_job_cards_vehicle_id')
        batch_op.drop_index('ix_job_cards_status')
        batch_op.drop_index('ix_job_cards_project_id')
        batch_op.drop_index('ix_job_cards_owner_id')
        batch_op.drop_index('ix_job_cards_client_id')
        batch_op.drop_index('ix_job_cards_category_id')
        batch_op.drop_column('quote_id')

    with op.batch_alter_table('job_card_time_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_time_entries_user_id')
        batch_op.drop_index('ix_time_entries_job_card_id')

    with op.batch_alter_table('job_card_materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_product_id')
        batch_op.drop_index('ix_materials_job_card_id')

    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_uploaded_by')
        batch_op.drop_index('ix_attachments_job_card_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quote_id')

    # ### end Alembic commands ###
