"""Add energy_scale_factor to projects

Revision ID: 194692801ba3
Revises: b0c0c18b550e
Create Date: 2025-09-03 10:29:52.309641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194692801ba3'
down_revision = 'b0c0c18b550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_scale_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('energy_scale_factor')

    # ### end Alembic commands ###
