"""added attachment_type to JobCardAttachment

Revision ID: 1957ac2f7117
Revises: d503d9dc93d3
Create Date: 2025-10-07 11:17:58.601796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1957ac2f7117'
down_revision = 'd503d9dc93d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.drop_column('attachment_type')

    # ### end Alembic commands ###
