"""Add products_test table for import validation

Revision ID: 1d04b6a84eee
Revises: ac306434a6ed
Create Date: 2025-07-16 11:31:01.440808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d04b6a84eee'
down_revision = 'ac306434a6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('rating_kva', sa.Float(), nullable=True),
    sa.Column('capacity_kwh', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('warranty_y', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_test_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_test_category'))

    op.drop_table('products_test')
    # ### end Alembic commands ###
