"""added source for job card materials

Revision ID: 3e1ae3aa341c
Revises: c8747479db7f
Create Date: 2025-10-29 14:12:58.078330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3e1ae3aa341c'
down_revision = 'c8747479db7f'
branch_labels = None
depends_on = None


def upgrade():
    materialsource = postgresql.ENUM('warehouse', 'store', name='materialsource')
    materialsource.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_material_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_material_receipts_attachment_id', ['attachment_id'], unique=False)
        batch_op.create_index('ix_material_receipts_material_id', ['material_id'], unique=False)
        batch_op.create_unique_constraint('uq_material_receipt_link', ['material_id', 'attachment_id'])

    with op.batch_alter_table('job_card_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('warehouse', 'store', name='materialsource', native_enum=True, create_constraint=False), nullable=False, server_default='warehouse'))
        batch_op.create_index('ix_materials_source', ['source'], unique=False)

    op.alter_column('job_card_materials', 'source', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_source')
        batch_op.drop_column('source')

    with op.batch_alter_table('job_card_material_receipts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_material_receipt_link', type_='unique')
        batch_op.drop_index('ix_material_receipts_material_id')
        batch_op.drop_index('ix_material_receipts_attachment_id')

    # ### end Alembic commands ###
