"""Add QuickDesignData table and update LoadProfiles

Revision ID: 3f8174160cde
Revises: 
Create Date: 2025-06-12 15:23:11.570600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f8174160cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_design_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('tariff', sa.Float(), nullable=True),
    sa.Column('consumer_type', sa.String(length=50), nullable=True),
    sa.Column('transformer_size', sa.Float(), nullable=True),
    sa.Column('selected_profile_id', sa.Integer(), nullable=True),
    sa.Column('selected_system_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selected_profile_id'], ['load_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('energy_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('projects_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('projects_client_id_fkey'), 'clients', ['client_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('energy_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.drop_table('quick_design_data')
    # ### end Alembic commands ###
