"""Add bom_modified field to Projects table

Revision ID: 48ef5379c11f
Revises: 6a197fa1410a
Create Date: 2025-08-19 08:59:32.965596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ef5379c11f'
down_revision = '6a197fa1410a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bom_modified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('bom_modified')

    # ### end Alembic commands ###
