"""add panel_id to projects

Revision ID: 50031782dad0
Revises: 9a515a0b960a
Create Date: 2025-08-11 11:09:38.016976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50031782dad0'
down_revision = '9a515a0b960a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['panel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('panel_id')

    # ### end Alembic commands ###
