"""add job_card_id to Document class

Revision ID: 5d465ea13c3c
Revises: 81fe814746ff
Create Date: 2025-10-07 15:11:16.530424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d465ea13c3c'
down_revision = '81fe814746ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'job_cards', ['job_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_card_id')

    # ### end Alembic commands ###
