"""added margin and other fields to bom table

Revision ID: 5db45d25f713
Revises: 50031782dad0
Create Date: 2025-08-11 15:16:01.749450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db45d25f713'
down_revision = '50031782dad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_cost_at_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('priced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_components', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('priced_at')
        batch_op.drop_column('unit_cost_at_time')
        batch_op.drop_column('override_margin')

    # ### end Alembic commands ###
