"""Added address field to clients table

Revision ID: 68db1b832aea
Revises: c766c3f63b9d
Create Date: 2025-08-21 12:04:41.601122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68db1b832aea'
down_revision = 'c766c3f63b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
