"""Added num panels field to Projects table

Revision ID: 6a197fa1410a
Revises: d4edab6161c7
Create Date: 2025-08-18 23:52:57.085176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a197fa1410a'
down_revision = 'd4edab6161c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_panels', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('num_panels')

    # ### end Alembic commands ###
