"""Uploaded newest products table

Revision ID: 6a7f07bf97d0
Revises: f7fa553ac959
Create Date: 2025-08-05 09:22:08.362159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a7f07bf97d0'
down_revision = '91bd772e44bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Component Type', sa.String(length=50), nullable=True),
    sa.Column('Brand Name', sa.String(length=80), nullable=True),
    sa.Column('Description', sa.String(length=300), nullable=True),
    sa.Column('Notes', sa.String(length=300), nullable=True),
    sa.Column('Supplier', sa.String(length=80), nullable=True),
    sa.Column('Updated', sa.String(length=30), nullable=True),
    sa.Column('Unit Cost', sa.Float(), nullable=True),
    sa.Column('QTY', sa.Integer(), nullable=True),
    sa.Column('Margin', sa.Float(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('Power Rating (W)', sa.Float(), nullable=True),
    sa.Column('Isc (A)', sa.Float(), nullable=True),
    sa.Column('Max Voc (V)', sa.Float(), nullable=True),
    sa.Column('Imp (A)', sa.Float(), nullable=True),
    sa.Column('Vmp', sa.Float(), nullable=True),
    sa.Column('Number Of Phases', sa.Integer(), nullable=True),
    sa.Column('Power Rating (kVA)', sa.Float(), nullable=True),
    sa.Column('Number of Inputs', sa.Integer(), nullable=True),
    sa.Column('Max Input Current per Input (A)', sa.Float(), nullable=True),
    sa.Column('Number of MPPT', sa.Integer(), nullable=True),
    sa.Column('Max Input Current per MPPT (A)', sa.Float(), nullable=True),
    sa.Column('Max Isc per MPPT (A)', sa.Float(), nullable=True),
    sa.Column('Max DC Input Voltage per MPPT (V)', sa.Float(), nullable=True),
    sa.Column('Min Operating Voltage Range (V)', sa.Float(), nullable=True),
    sa.Column('Max Operating Voltage Range (V)', sa.Float(), nullable=True),
    sa.Column('Rated Input Voltage (V)', sa.Float(), nullable=True),
    sa.Column('Nominal Rating (kWh)', sa.Float(), nullable=True),
    sa.Column('Usable Rating (kWh)', sa.Float(), nullable=True),
    sa.Column('Nominal Voltage (V)', sa.Float(), nullable=True),
    sa.Column('Nominal Amperage (A)', sa.Float(), nullable=True),
    sa.Column('Poles', sa.Integer(), nullable=True),
    sa.Column('Interrupting Capacity (kA)', sa.Float(), nullable=True),
    sa.Column('Min Current Rating (A)', sa.Float(), nullable=True),
    sa.Column('Max Current Rating (A)', sa.Float(), nullable=True),
    sa.Column('Voltage Rating (V)', sa.Float(), nullable=True),
    sa.Column('Rated Voltage (V)', sa.Float(), nullable=True),
    sa.Column('Nominal Current (A)', sa.Float(), nullable=True),
    sa.Column('Number of Poles', sa.Integer(), nullable=True),
    sa.Column('Mounting Type', sa.String(length=80), nullable=True),
    sa.Column('Cable Type', sa.String(length=80), nullable=True),
    sa.Column('Cable Size (mm2)', sa.Float(), nullable=True),
    sa.Column('Cores (AC Cable)', sa.Integer(), nullable=True),
    sa.Column('Ampacity at 30C', sa.Float(), nullable=True),
    sa.Column('Current Rating (Ground) [A]', sa.Float(), nullable=True),
    sa.Column('Current Rating (Air) [A]', sa.Float(), nullable=True),
    sa.Column('Current Rating (Duct) [A]', sa.Float(), nullable=True),
    sa.Column('Impedance (Ohm/km)', sa.Float(), nullable=True),
    sa.Column('3 Phase Volt Drop (mV/A/m)', sa.Float(), nullable=True),
    sa.Column('1 Phase Volt Drop (mV/A/m)', sa.Float(), nullable=True),
    sa.Column('D1', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.Column('D2', sa.Float(), nullable=True),
    sa.Column('Mass (kg/km)', sa.Float(), nullable=True),
    sa.Column('Insulation/Sheath', sa.String(length=80), nullable=True),
    sa.Column('Armour', sa.String(length=80), nullable=True),
    sa.Column('Working voltage (phase to earth) - AC Cable', sa.Float(), nullable=True),
    sa.Column('Working voltage (phase to phase) - AC Cable', sa.Float(), nullable=True),
    sa.Column('Core', sa.String(length=40), nullable=True),
    sa.Column('Cross Section (mm2)', sa.Float(), nullable=True),
    sa.Column('Current Rating (A)', sa.Float(), nullable=True),
    sa.Column('Voltage Drop (V/A/km)', sa.Float(), nullable=True),
    sa.Column('Max Outer Diam (mm)', sa.Float(), nullable=True),
    sa.Column('Weight (kg/km)', sa.Float(), nullable=True),
    sa.Column('Resistance (Ω/km)', sa.Float(), nullable=True),
    sa.Column('Working voltage (phase to earth) - H07RN-F', sa.Float(), nullable=True),
    sa.Column('Working voltage (phase to phase) - H07RN-F', sa.Float(), nullable=True),
    sa.Column('Copper Cross Section (mm2)', sa.Float(), nullable=True),
    sa.Column('Organiser Series', sa.String(length=80), nullable=True),
    sa.Column('Organiser Length (m)', sa.Float(), nullable=True),
    sa.Column('Organiser Width (mm)', sa.Float(), nullable=True),
    sa.Column('Organiser Height (mm)', sa.Float(), nullable=True),
    sa.Column('Organiser Colour', sa.String(length=40), nullable=True),
    sa.Column('Material/Duty', sa.String(length=80), nullable=True),
    sa.Column('Mount Context', sa.String(length=80), nullable=True),
    sa.Column('Roof Interface', sa.String(length=80), nullable=True),
    sa.Column('Mount Type', sa.String(length=80), nullable=True),
    sa.Column('Tilt Angle (deg)', sa.Float(), nullable=True),
    sa.Column('Has Base Rails', sa.Boolean(), nullable=True),
    sa.Column('Ballasted Mount', sa.Boolean(), nullable=True),
    sa.Column('Switch Min Current Rating', sa.Float(), nullable=True),
    sa.Column('Switch Mx Current Rating', sa.Float(), nullable=True),
    sa.Column('Switchover Poles', sa.Integer(), nullable=True),
    sa.Column('Voltage', sa.Float(), nullable=True),
    sa.Column('Enclosure Width (mm)', sa.Float(), nullable=True),
    sa.Column('Enclosure Height (mm)', sa.Float(), nullable=True),
    sa.Column('Enclosure Depth (mm)', sa.Float(), nullable=True),
    sa.Column('IP Rating', sa.String(length=20), nullable=True),
    sa.Column('Door Type', sa.String(length=50), nullable=True),
    sa.Column('DB Width (mm)', sa.Float(), nullable=True),
    sa.Column('DB Height (mm)', sa.Float(), nullable=True),
    sa.Column('DB Depth (mm)', sa.Float(), nullable=True),
    sa.Column('DB Mounting Type', sa.String(length=50), nullable=True),
    sa.Column('DB Weatherproof Rating', sa.String(length=50), nullable=True),
    sa.Column('DB Modular Size', sa.Integer(), nullable=True),
    sa.Column('Voltage Class', sa.String(length=50), nullable=True),
    sa.Column('Current Rating', sa.Float(), nullable=True),
    sa.Column('MPPT Communication', sa.String(length=80), nullable=True),
    sa.Column('Enclosure', sa.String(length=80), nullable=True),
    sa.Column('MPPT Application', sa.String(length=80), nullable=True),
    sa.Column('Mounting', sa.String(length=80), nullable=True),
    sa.Column('Function', sa.String(length=80), nullable=True),
    sa.Column('Control Communication', sa.String(length=80), nullable=True),
    sa.Column('Model Code / SKU', sa.String(length=120), nullable=True),
    sa.Column('Control Application', sa.String(length=80), nullable=True),
    sa.Column('Monitoring Function', sa.String(length=80), nullable=True),
    sa.Column('Monitoring Communication', sa.String(length=80), nullable=True),
    sa.Column('Monitoring Application', sa.String(length=80), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['subject_product_id'], ['id'])

    with op.batch_alter_table('system_template_components', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_template_components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('component_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('products')
    # ### end Alembic commands ###
