"""added recycle bin columns to projects table

Revision ID: 7f7d9c91b3c7
Revises: 7ba2b2c7d819
Create Date: 2025-10-08 09:16:13.972991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7d9c91b3c7'
down_revision = '7ba2b2c7d819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['deleted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
