"""added status to jobcards

Revision ID: 81298bf87dea
Revises: 7f7d9c91b3c7
Create Date: 2025-10-09 09:29:39.301673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81298bf87dea'
down_revision = '7f7d9c91b3c7'
branch_labels = None
depends_on = None
PENDING = "pending"
APPROVED = "approved"
NEEDS_FIX = "needs_fix"
DECLINED = "declined"

def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE jobcardreviewstatus AS ENUM ('pending', 'approved', 'needs_fix', 'declined')")
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bum_status', sa.Enum('pending', 'approved', 'needs_fix', 'declined', name='jobcardreviewstatus'), nullable=False))
        batch_op.add_column(sa.Column('bum_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bum_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bum_reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['bum_reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bum_reviewed_by_id')
        batch_op.drop_column('bum_reviewed_at')
        batch_op.drop_column('bum_comment')
        batch_op.drop_column('bum_status')

    op.execute("DROP TYPE jobcardreviewstatus")

    # ### end Alembic commands ###
