"""added caption to jobcardAttachment

Revision ID: 81fe814746ff
Revises: 1957ac2f7117
Create Date: 2025-10-07 11:37:20.618104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fe814746ff'
down_revision = '1957ac2f7117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_card_attachments', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
