"""add invoice tables

Revision ID: 835938d8978d
Revises: 9a45d7ab17b4
Create Date: 2025-10-13 13:02:38.915563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835938d8978d'
down_revision = '9a45d7ab17b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('quote_number', sa.String(length=50), nullable=True),
    sa.Column('quote_version', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('percent_of_quote', sa.Float(), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('billing_company', sa.String(length=255), nullable=True),
    sa.Column('billing_vat_no', sa.String(length=64), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subtotal_excl_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_incl_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price_excl_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total_excl_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total_incl_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
