"""added warranty column to products

Revision ID: 87a94c0ffef5
Revises: c9ef245080ae
Create Date: 2025-08-19 15:00:56.587194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a94c0ffef5'
down_revision = 'c9ef245080ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Warranty (y)', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('Warranty (y)')

    # ### end Alembic commands ###
