"""Add job_card_id to Invoice Model

Revision ID: 9269a04048ab
Revises: 835938d8978d
Create Date: 2025-10-14 16:27:31.081221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9269a04048ab'
down_revision = '835938d8978d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'job_cards', ['job_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_card_id')

    # ### end Alembic commands ###
