"""Add profile scaler to QuickDesignData

Revision ID: 9695ecd63936
Revises: e6a526aa6181
Create Date: 2025-06-13 16:02:11.627883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9695ecd63936'
down_revision = 'e6a526aa6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_design_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_scaler', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_design_data', schema=None) as batch_op:
        batch_op.drop_column('profile_scaler')

    # ### end Alembic commands ###
