"""sync changes

Revision ID: 9a45d7ab17b4
Revises: 006f14622c47
Create Date: 2025-10-13 10:10:41.924601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a45d7ab17b4'
down_revision = '006f14622c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('energy_data', schema=None) as batch_op:
    #     batch_op.alter_column('project_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('properties',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))

    with op.batch_alter_table('energy_data', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
