"""Add template fields to projects model

Revision ID: 9a515a0b960a
Revises: 75aa9f905fe3
Create Date: 2025-08-08 14:47:24.409180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a515a0b960a'
down_revision = '75aa9f905fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_standard_template', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('template_name')
        batch_op.drop_column('template_id')
        batch_op.drop_column('from_standard_template')

    # ### end Alembic commands ###
