"""Add monthly_avg_kwh_original and max_peak_demand_kw to load_profiles

Revision ID: a7e93891a930
Revises: a8bcea0d18f5
Create Date: 2025-08-18 12:13:51.446770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e93891a930'
down_revision = 'a8bcea0d18f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_avg_kwh_original', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_peak_demand_kw', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_profiles', schema=None) as batch_op:
        batch_op.drop_column('max_peak_demand_kw')
        batch_op.drop_column('monthly_avg_kwh_original')

    # ### end Alembic commands ###
