"""added quote number and version to bomcomponents

Revision ID: a8bcea0d18f5
Revises: 5db45d25f713
Create Date: 2025-08-12 08:29:46.326494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bcea0d18f5'
down_revision = '5db45d25f713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quote_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_components', schema=None) as batch_op:
        batch_op.drop_column('quote_version')
        batch_op.drop_column('quote_number')

    # ### end Alembic commands ###
