"""Bum fields and materials added

Revision ID: ac642f3d8f5d
Revises: e7ca7c311f84
Create Date: 2025-10-02 13:04:08.229657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac642f3d8f5d'
down_revision = 'e7ca7c311f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_card_material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['job_card_attachments.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['job_card_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_job_cards_bum'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['bum_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_cards_bum'), 'users', ['bum_id'], ['id'], ondelete='SET NULL')

    op.drop_table('job_card_material_receipts')
    # ### end Alembic commands ###
