"""Added vat number and company to clients table

Revision ID: be699ba230ed
Revises: 194692801ba3
Create Date: 2025-09-05 13:00:35.907417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be699ba230ed'
down_revision = '194692801ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vat_number', sa.String(length=30), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('energy_scale_factor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_scale_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('vat_number')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
