"""add review status for quotes

Revision ID: c8747479db7f
Revises: 0b59911cc118
Create Date: 2025-10-29 10:58:31.818122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8747479db7f'
down_revision = '0b59911cc118'
branch_labels = None
depends_on = None

# Define the new ENUM type for use in the migration
quote_review_status_enum = sa.Enum('NONE', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='quotereviewstatus')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create the new ENUM type in the database before it's used
    quote_review_status_enum.create(op.get_bind())

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        # 2. Add the columns, using the new type and providing a server_default for existing rows
        batch_op.add_column(sa.Column('review_status', quote_review_status_enum, nullable=False, server_default='NONE'))
        batch_op.add_column(sa.Column('review_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_comments', sa.Text(), nullable=True))
        
        # 3. Create foreign keys with explicit names
        batch_op.create_foreign_key('fk_doc_versions_review_requested_by_id', 'users', ['review_requested_by_id'], ['id'])
        batch_op.create_foreign_key('fk_doc_versions_reviewed_by_id', 'users', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        # 1. Drop foreign keys using their explicit names
        batch_op.drop_constraint('fk_doc_versions_reviewed_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_doc_versions_review_requested_by_id', type_='foreignkey')
        
        # 2. Drop the columns
        batch_op.drop_column('reviewer_comments')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('review_requested_by_id')
        batch_op.drop_column('review_status')

    # 3. Drop the ENUM type from the database after it's no longer in use
    quote_review_status_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
