"""Initial database schema

Revision ID: d00eeffa1866
Revises: 
Create Date: 2025-07-09 16:44:20.719221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd00eeffa1866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('load_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('annual_kwh', sa.Float(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('rating_kva', sa.Float(), nullable=True),
    sa.Column('capacity_kwh', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('warranty_y', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)

    op.create_table('system_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=True),
    sa.Column('extras_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('power_user_type', sa.String(length=50), nullable=True),
    sa.Column('tariff_category', sa.String(length=100), nullable=True),
    sa.Column('transmission_zone', sa.String(length=100), nullable=True),
    sa.Column('supply_voltage', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('matrix_code', sa.String(length=50), nullable=True),
    sa.Column('structure', sa.String(length=50), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('system_type', sa.String(length=20), nullable=True),
    sa.Column('panel_kw', sa.Float(), nullable=True),
    sa.Column('inverter_kva', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('battery_kwh', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inverter_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('battery_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_value_excl_vat', sa.Float(), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('custom_flat_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('site_contact_person', sa.String(length=80), nullable=True),
    sa.Column('site_phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('design_type', sa.String(length=20), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_template_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['system_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('charge_name', sa.String(length=150), nullable=False),
    sa.Column('charge_category', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('time_of_use', sa.String(length=50), nullable=True),
    sa.Column('rate_unit', sa.String(length=50), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('block_threshold_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_rates_charge_category'), ['charge_category'], unique=False)

    op.create_table('energy_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('demand_kw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('system_type', sa.String(length=20), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('best_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_design_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('tariff', sa.Float(), nullable=True),
    sa.Column('consumer_type', sa.String(length=50), nullable=True),
    sa.Column('transformer_size', sa.Float(), nullable=True),
    sa.Column('selected_profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_scaler', sa.Float(), nullable=True),
    sa.Column('selected_system_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selected_profile_id'], ['load_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_design_data')
    op.drop_table('optimization_runs')
    op.drop_table('energy_data')
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_rates_charge_category'))

    op.drop_table('tariff_rates')
    op.drop_table('system_template_components')
    op.drop_table('projects')
    op.drop_table('tariffs')
    op.drop_table('system_templates')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    op.drop_table('load_profiles')
    op.drop_table('clients')
    # ### end Alembic commands ###
