"""Add profile_id and profile_scaler to Projects

Revision ID: d503d9dc93d3
Revises: ac642f3d8f5d
Create Date: 2025-10-06 11:54:22.751326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd503d9dc93d3'
down_revision = 'ac642f3d8f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_scaler', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'load_profiles', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_scaler')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
