"""Added is_quoted to JobCard table

Revision ID: daec9a7449c8
Revises: 275825c0c3e2
Create Date: 2025-09-30 11:32:26.322051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daec9a7449c8'
down_revision = '275825c0c3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quoted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_column('is_quoted')

    # ### end Alembic commands ###
