"""Added extras cost to SystemsTemplate table

Revision ID: e6a526aa6181
Revises: 9c46bbcfa98f
Create Date: 2025-06-13 11:18:13.980145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a526aa6181'
down_revision = '9c46bbcfa98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extras_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_templates', schema=None) as batch_op:
        batch_op.drop_column('extras_cost')

    # ### end Alembic commands ###
