"""Add tilt and azimuth to projects

Revision ID: e70591210d1e
Revises: 4f2fa755e9c2
Create Date: 2025-07-14 15:57:11.044738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70591210d1e'
down_revision = '4f2fa755e9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_tilt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('surface_azimuth', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('surface_azimuth')
        batch_op.drop_column('surface_tilt')

    # ### end Alembic commands ###
