"""add bum_id to users and jobcards models

Revision ID: e7ca7c311f84
Revises: a835be31580f
Create Date: 2025-10-01 14:52:57.483460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ca7c311f84'
down_revision = 'a835be31580f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bum_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_job_cards_bum", "users", ["bum_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bum', sa.Boolean(), nullable=False, server_default=sa.text("false")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_bum')

    with op.batch_alter_table('job_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bum_id')

    # ### end Alembic commands ###
