"""Add tariffs and tariff_rates tables

Revision ID: f89bd5e2bc6b
Revises: 9695ecd63936
Create Date: 2025-07-09 09:56:31.147391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89bd5e2bc6b'
down_revision = '9695ecd63936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('power_user_type', sa.String(length=50), nullable=True),
    sa.Column('tariff_category', sa.String(length=100), nullable=True),
    sa.Column('transmission_zone', sa.String(length=100), nullable=True),
    sa.Column('supply_voltage', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('matrix_code', sa.String(length=50), nullable=True),
    sa.Column('structure', sa.String(length=50), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('charge_name', sa.String(length=150), nullable=False),
    sa.Column('charge_category', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('time_of_use', sa.String(length=50), nullable=True),
    sa.Column('rate_unit', sa.String(length=50), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('block_threshold_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_rates_charge_category'), ['charge_category'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tariffs', ['tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tariff_id')

    with op.batch_alter_table('tariff_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_rates_charge_category'))

    op.drop_table('tariff_rates')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
